

server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://mysql-container:3306/prediction
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  thymeleaf:
    servlet:
      produce-partial-output-while-processing: false